### ISSUE TITLE
Overlay not going to work well on map & not possible on camera

### ISSUE THREAD

**Issue by meggrasse** [NUDelta/rppt-web#10]
Line 216-220 in https://github.com/Finnja/topcode-rppt/blob/master/web/dart/main.dart needs to be fixed for map (need to add callTransparency flag and turn it off when screenshot is called so we aren't constantly sending screenshots). Needs to be added all together for camera.

**Comment by haoqizhang** [comment]
as meg points out, overlay on camera would actually be super cool because you all of a sudden get all of camera-based Augmented Reality.

**Comment by meggrasse** [comment]
Using different codes for each element so we can have multiple multi-fidelity elements at the same time (maps with pins while have photo with mustache elsewhere on screen)

**Comment by meggrasse** [comment]
9737b89cbaf0b6eb99be4d124232c39f2c0f210c + corresponding commit on iOS
