### ISSUE TITLE
multi-fidelity element overlay shows topcodes in corner over digital element

### ISSUE THREAD

**Issue by kaldjian** [NUDelta/rppt-web#13]
Transparency function needs to take into account the size of the topcodes in each corner so that they do not come through as overlays. See top and bottom right corners of attached image.

<img width="1280" alt="screen_shot_2017-03-29_at_8 17 13_pm" src="https://cloud.githubusercontent.com/assets/7905396/24522658/dc819c02-1555-11e7-8e71-aa549aab2873.png">

**Comment by meggrasse** [comment]
Fixed in 89d3af02f8027cc222f5818dad3ec69a2d5573d2
