### ISSUE TITLE
Refine CC front-end to be clearer for wizard

### ISSUE THREAD

**Issue by meggrasse** [NUDelta/rppt-web#14]
Since we added/removed some features from RPPT, we should change the CC organization to be more clear to wizard. Here's what we were thinking

Left pane:
- Stream Key
- Blue button to turn on detection (maybe with a label)
- Preview from webcam labeled as such (what currently sits at bottom left)

Middle:
- Stream from iPhone labeled as such

Right:
- User messages
- Map

Get rid of Glass div + QR code for glass

**Comment by haoqizhang** [comment]
anonymize --take out kevin's name and also delta logo
