### ISSUE TITLE
Lag in multifidelity feature

### ISSUE THREAD

**Issue by meggrasse** [NUDelta/rppt-web#5]
To overlay physical modifications on digital elements we have a method that "extracts" physical drawings on digital elements. We do so by changing every white pixel to transparent to extract the image. However we do so in a for-loop (very slow) -- mapping function would work better. The issue is in whiteToTransparent() in paper_stream.js.

**Comment by haoqizhang** [comment]
As I understand it the current way multi-fidelity elements works is:

1. place a digital element on paper with top codes
2. place physical elements on top of it (pins, mustaches, etc)
3. place a separate top code on top, to "signal" to the system that physical elements have been overlaid.
4. the algorithm runs to isolate and segment the physical elements on a canvas  [this is the part thats slow]
5. the segmented image is sent to iOS to display on top as a overlay

**Comment by haoqizhang** [comment]
this is highest priority

**Comment by aspin** [comment]
to leave a note of thoughts before I look into more stuff later:
 * don't mutate imageData object -- not sure if changes attempt to trigger a canvas update (probably not; map should take care of this)
 * can offload work to webworker if operation affects the rest of the page's functionality
 * last option is to find a more efficient transparency algorithm

**Comment by sliminality** [comment]
Fixed in #8. `console.log` is your enemy when it happens 20,000 times.
