### ISSUE TITLE
Multi-fidelity element stays and doesn't reset

### ISSUE THREAD

**Issue by haoqizhang** [NUDelta/rppt-web#6]
As I understand it the current way multi-fidelity elements works is:

1. place a digital element on paper with top codes
2. place physical elements on top of it (pins, mustaches, etc)
3. place a separate top code on top, to "signal" to the system that physical elements have been overlaid.
4. the algorithm runs to isolate and segment the physical elements on a canvas 
5. the segmented image is sent to iOS to display on top as a overlay

There is no way to remove the physical element placed on top once it's displayed. Here is one possible approach
- When the top code that "signals the system of the physical element is removed, it should remove the physical elements from the rendering in iOS.
- Now the physical elements can be moved
- And then place the top code to signal they are back.

(the problem with this approach through is that it will flicker). Can we get direct changes automatically without it being slow?  Will have to fix the prior issue first.

**Comment by haoqizhang** [comment]
fix issue #5 first.

**Comment by haoqizhang** [comment]
One simple fix is to have another topcode to "take off the overlay", which should call iOS to remove the draw, and also reset the call transparency flag.

And then, the paper can be removed, and then the topcode for "hey i have an overlay" triggers, as it does before.

**Comment by meggrasse** [comment]
Another simple fix would have it take + send screenshot of physical every 5 frames or so. iOS would then throw out old image and replace with new one once one is sent.

**Comment by meggrasse** [comment]
Update: because of Sarah's fix overlays update in (almost) real-time! It would be nice if there was a way to stop detection of overlays but not really necessary.

I would change this bug to low priority.

**Comment by kaldjian** [comment]
Update 2: overlays disappear when their corresponding element is taken out of frame. It would be nice to stop detection but really this is not a priority at all.

**Comment by aspin** [comment]
#7 was fixed not this by that PR

**Comment by meggrasse** [comment]
Currently, overlays update dynamically. Server methods to remove overlays are called (1) when the overlay TopCode is no longer detected or (2) when the native component of the MF element is no longer detected (a095dc20133e9e67e55111dfb0f3391df525b580 in the rppt-web project). The overlay UIImageView then removed based on the server call (eae99c1dabf5711f11f66baf223c1a0d0484a003 in the rppt-ios project).
