### ISSUE TITLE
Video stream -> iOS coordinates not perfect

### ISSUE THREAD

**Issue by meggrasse** [NUDelta/rppt-web#7]
Approximated the mappings of coordinates in video stream -> coordinates on iOS side. Not perfect. Coordinates determined on line 186-202 https://github.com/Finnja/topcode-rppt/blob/master/web/dart/main.dart

**Comment by meggrasse** [comment]
Possible culprits: not taking into account status bar (check that the top of the screen works), incorrect algorithm (bad scaling or bad bounds;  199-202)

Added and subtracted radius (we believe correctly) lines 189-196.

**Comment by meggrasse** [comment]
Also applies to image gotten from multi-fidelity

**Comment by aspin** [comment]
fixed by PR #12

**Comment by meggrasse** [comment]
Looks better - but added some testing screenshots for reference.

Looks like maybe some radius issues for the bottom codes?

For the map: 
![screen shot 2017-03-30 at 2 49 21 pm](https://cloud.githubusercontent.com/assets/12224338/24523563/10f73b2e-1559-11e7-8c4f-b384641b9c04.png)
![screen shot 2017-03-30 at 2 48 23 pm](https://cloud.githubusercontent.com/assets/12224338/24523564/10f8ffb8-1559-11e7-9b38-ab567e1712e5.png)
![screen shot 2017-03-30 at 2 49 03 pm](https://cloud.githubusercontent.com/assets/12224338/24523565/10f9189a-1559-11e7-9253-0f933def60a4.png)

**Comment by aspin** [comment]
weird i'll take another look

**Comment by aspin** [comment]
wait is this only for the map?

**Comment by meggrasse** [comment]
Further fixed in 9ccb004620963220056516b8c77af8d4a5abd681
